# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

arr = np.arange(10)
arr2d = arr.reshape(2,5)

arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
arr1 = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])

vstack_arr = np.vstack((arr1,arr2))
vstack_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
array2d = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

array1d = np.ravel(array2d)
array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [23]:
arr = np.arange(15).reshape(3,5)

arr1d = arr.reshape(15)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
a = np.arange(15)

b = a.reshape(5,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [9]:
array = np.arange(25).reshape(5,5)
print(array)

array_square = np.square(array)
array_square

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [10]:
array = np.arange(30).reshape(5,6)
print(array)

array_mean = np.mean(array)
array_mean

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [15]:
array = np.arange(30).reshape(5,6)
print(array)

array_std = np.std(array)
array_std

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [14]:
array = np.arange(30).reshape(5,6)
print(array)

array_median = np.median(array)
array_median

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [13]:
array = np.arange(30).reshape(5,6)
print(array)

array_trans = array.transpose()
array_trans

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [16]:
arr = np.arange(16).reshape(4,4)
print(arr)

sum_diagonal = np.trace(arr)
sum_diagonal

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [17]:
arr = np.arange(16).reshape(4,4)
print(arr)

det_arr = np.linalg.det(arr)
det_arr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [21]:
array = np.array([1,2,3,5,8,4])

print(np.percentile(array, 5))
print(np.percentile(array, 95))


1.25
7.25


## Question:15

### How to find if a given array has any null values?

In [20]:
array = np.array([1,2,3,5,np.nan])

np.isnan(array)

array([False, False, False, False,  True])